---
- name: install required tools
  apt:
    name: 
    - gnupg
    - git
    - python3
    - python3-pip
    state: latest
    update_cache: yes

- name: add GoCD and c3voc apt-keys
  apt_key: 
    url: "{{ item }}"
    state: present 
  with_items:
    - https://download.gocd.org/GOCD-GPG-KEY.asc
    - https://pkg.c3voc.de/repo.key


- name: add repositories to the sources
  apt_repository: 
    repo: "{{ item }}"
    state: present 
    update_cache: yes  
  with_items:
    - deb https://download.gocd.org /
    - deb http://pkg.c3voc.de/ ffmpeg-bullseye main
    - deb http://pkg.c3voc.de/ bullseye main

- name: install packages
  apt: 
    name: 
     - go-agent
     - ffmpeg
    state: latest
    update_cache: yes
- name: Install required python3 modules
  pip:
    name:
      - pillow
    executable: pip3
  become: yes
  become_user: go
    


- name: configuring the GoCD agent
  lineinfile:
    path: /usr/share/go-agent/wrapper-config/wrapper-properties.conf
    regexp: '^wrapper.app.parameter.101'
    line: wrapper.app.parameter.101=https://videopipeline.freifunk.net/go/

- name: copying the processing scripts to /opt folder
  copy:
    src: "{{ playbook_dir }}/../scripts/"
    dest: /opt/

- name: start gocd-agent service
  service:
    name: go-agent
    state: restarted