format_version: 10
pipelines:
  test-processing-pipeline:
    group: videoodyssee
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-58b26e2:
        git: https://github.com/0xVijayReddy/test.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - processing:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        environment_variables:
          video_url: http://techslides.com/demos/sample-videos/small.mp4
          video_id: dd3456dd-e277-4947-95db-3b7c64d4216f
          title: Test
        jobs:
          encode-h264:
            timeout: 0
            artifacts:
            - build:
                source: '*h264.mp4'
                destination: ''
            tasks:
            - exec:
                arguments:
                - download_video.sh
                command: bash
                run_if: passed
            - exec:
                arguments:
                - encode_h264_AAC_HQ.sh
                command: bash
                run_if: passed
            - exec:
                arguments:
                - fix-metadata.sh
                command: bash
                run_if: passed
            - exec:
                command: pwd
                run_if: passed
            - exec:
                command: ls
                run_if: passed
