format_version: 10
pipelines:
  publishing-pipeline:
    group: sample-pipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-317d973:
        git: https://github.com/0xVijayReddy/test.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - publish-video:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          publish-to-youtube:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed