all:
  children:
    gocd-server:
      hosts:
        videopipeline.freifunk.net:
          domains:
            - videopipeline.freifunk.net
          email: web+videopipeline@freifunk.net
    gocd-agent:
      hosts:
        # 13.127.28.22:
        # 43.205.117.34:
        videopipeline.freifunk.net
      # vars:
      #   ansible_user: admin  
      #   ansible_ssh_private_key_file: ~/.ssh/login.pem
 