all:
  children:
    gocd-server:
      hosts:
        videopipeline.freifunk.net:
          domains:
            - videopipeline.freifunk.net
          email: web+videopipeline@freifunk.net
    gocd-agent:
      hosts:
        3.111.196.227:
      vars:
        ansible_user: admin  
        ansible_ssh_private_key_file: ~/Downloads/new.pem
 